query {
  objects: __schema {
     types {
      name
            enumValues {
        name
      }
      ofType {
        name
        ofType{
          name
          
          ofType {
            name
          }
        }
      }
      fields {
        name
        type {
          name
          description
          ofType{
            name
            ofType {
              name
              ofType {
                name
        
              }
            }
          }
        }
      }
      kind
    }
  }

}